from .policy import ToolMetadata


# AgentDojo v1.2.2 banking suite 的静态工具属性。
BANKING_TOOL_METADATA: dict[str, ToolMetadata] = {
    "get_iban": ToolMetadata(
        name="get_iban",
        side_effect="read",
        scope="local",
        reversibility="reversible",
        sensitive_args=(),
        impact=1,
    ),
    "get_balance": ToolMetadata(
        name="get_balance",
        side_effect="read",
        scope="local",
        reversibility="reversible",
        sensitive_args=(),
        impact=1,
    ),
    "get_most_recent_transactions": ToolMetadata(
        name="get_most_recent_transactions",
        side_effect="read",
        scope="local",
        reversibility="reversible",
        sensitive_args=("n",),
        impact=1,
    ),
    "get_scheduled_transactions": ToolMetadata(
        name="get_scheduled_transactions",
        side_effect="read",
        scope="local",
        reversibility="reversible",
        sensitive_args=(),
        impact=1,
    ),
    "read_file": ToolMetadata(
        name="read_file",
        side_effect="read",
        scope="local",
        reversibility="reversible",
        sensitive_args=("file_path",),
        impact=1,
    ),
    "get_user_info": ToolMetadata(
        name="get_user_info",
        side_effect="read",
        scope="local",
        reversibility="reversible",
        sensitive_args=(),
        impact=1,
    ),
    "send_money": ToolMetadata(
        name="send_money",
        side_effect="write",
        scope="external",
        reversibility="irreversible",
        sensitive_args=("recipient", "amount", "subject", "date"),
        impact=4,
    ),
    "schedule_transaction": ToolMetadata(
        name="schedule_transaction",
        side_effect="write",
        scope="external",
        reversibility="irreversible",
        sensitive_args=("recipient", "amount", "subject", "date"),
        impact=4,
    ),
    "update_scheduled_transaction": ToolMetadata(
        name="update_scheduled_transaction",
        side_effect="write",
        scope="external",
        reversibility="irreversible",
        sensitive_args=("id", "recipient", "amount", "date"),
        impact=4,
    ),
    "update_password": ToolMetadata(
        name="update_password",
        side_effect="write",
        scope="local",
        reversibility="irreversible",
        sensitive_args=("password",),
        impact=4,
        destructive=True,
        intent_keywords=(
            "password",
            "reset",
            "change",
            "密码",
            "更新密码",
            "改密码",
            "重置密码",
        ),
    ),
    "update_user_info": ToolMetadata(
        name="update_user_info",
        side_effect="write",
        scope="local",
        reversibility="irreversible",
        sensitive_args=("first_name", "last_name", "street", "city"),
        impact=3,
    ),
}
